window.BNTI_DATA = {
  "meta": {
    "generated_at": "2026-07-20T15:52:32.741572",
    "main_index": 4.17,
    "status": "ELEVATED",
    "active_scan": false,
    "next_update": "2026-07-20T17:00:00",
    "version": "2.0.0"
  },
  "countries": {
    "Armenia": {
      "index": 1.63,
      "raw_score": 0.3,
      "events": [
        {
          "title": "When It Hails, It Pours: Livelihood of Armenia&#039;s Farmers at the Mercy of the Heavens",
          "translated_title": "When It Hails, It Pours: Livelihood of Armenia&#039;s Farmers at the Mercy of the Heavens",
          "link": "https://hetq.am/en/article/182780",
          "date": "Mon, 20 Jul 2026 19:05:00 +0400",
          "source_country": "Armenia",
          "category": "humanitarian_crisis",
          "weight": 3.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Farmers' livelihoods hit by hail",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Faces erased: Why Yerevan must preserve the memory of its fallen heroes",
          "translated_title": null,
          "link": "https://armenianweekly.com/2026/07/20/faces-erased-why-yerevan-must-preserve-the-memory-of-its-fallen-heroes/",
          "date": "Mon, 20 Jul 2026 15:18:07 +0000",
          "source_country": "Armenia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Yerevan preserving memory of fallen heroes",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Moko Khatchatryan’s inherited yet unique artistic signature",
          "translated_title": null,
          "link": "https://armenianweekly.com/2026/07/20/moko-khatchatryans-inherited-yet-unique-artistic-signature/",
          "date": "Mon, 20 Jul 2026 11:15:29 +0000",
          "source_country": "Armenia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Moko Khatchatryan artistic signature",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "«Հայաստանի 100 լավագույն ուսանողներ» մրցույթի արդյունքներն ամփոփվել են, «Կարապետյան» հիմնադրամը կպարգևատրի՝ մեկ տարվա ուսման վարձի չափով",
          "translated_title": null,
          "link": "https://www.aravot.am/2026/07/20/1569963/",
          "date": "Mon, 20 Jul 2026 15:30:26 +0000",
          "source_country": "Armenia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Armenia top students competition results",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Հայտնաբերվել է 516 ոչ սթափ վարորդ",
          "translated_title": null,
          "link": "https://www.aravot.am/2026/07/20/1569952/",
          "date": "Mon, 20 Jul 2026 15:15:17 +0000",
          "source_country": "Armenia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "516 drunk drivers detected in Armenia",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "10-ամյա Եվայի «հակապետական» նկարի արժեքը հասել է 1000 դոլարի",
          "translated_title": null,
          "link": "https://www.aravot.am/2026/07/20/1569959/",
          "date": "Mon, 20 Jul 2026 14:55:55 +0000",
          "source_country": "Armenia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Child's anti-state drawing value reaches 1000 dollars",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Յուրաքանչյուր կին պետք է ունենա հավասար հնարավորություն կրթություն ստանալու, աշխատելու, սեփական կարողություններն իրացնելու և հասարակական կյանքին լիարժեք մասնակցելու համար. ՄԻՊ",
          "translated_title": null,
          "link": "https://www.aravot.am/2026/07/20/1569956/",
          "date": "Mon, 20 Jul 2026 14:44:48 +0000",
          "source_country": "Armenia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Ombudsman on women's equal opportunities",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "«Սա զուտ անհատական է, պետք չէ դիտարկել՝ որպես պետական քաղաքականություն»․ թուրքագետը՝ Ստամբուլի Սկյուտար թաղամասի հայկական Սուրբ Կարապետ եկեղեցու գերեզմանատանը կատարված վանդալիզմի առիթով",
          "translated_title": null,
          "link": "https://www.aravot.am/2026/07/20/1569955/",
          "date": "Mon, 20 Jul 2026 14:33:52 +0000",
          "source_country": "Armenia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Vandalism at Armenian church graveyard in Istanbul",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Բյուրեղավան համայնքում ջրի 14 նմուշառման կետերից 3-ում արձանագրվել են շեղումներ",
          "translated_title": null,
          "link": "https://www.aravot.am/2026/07/20/1569950/",
          "date": "Mon, 20 Jul 2026 14:22:59 +0000",
          "source_country": "Armenia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Water sample deviations in Byureghavan",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Քննարկվել են կարկուտի հետևանքով վնասների գնահատման և այդ ուղղությամբ միջգերատեսչական համագործակցության հարցեր․ ամփոփվել է Փրկարար ծառայության Տավուշի վարչության կիսամյակային աշխատանքը",
          "translated_title": null,
          "link": "https://www.aravot.am/2026/07/20/1569939/",
          "date": "Mon, 20 Jul 2026 13:49:56 +0000",
          "source_country": "Armenia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Hail damage assessment and rescue service review",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        }
      ]
    },
    "Georgia": {
      "index": 2.75,
      "raw_score": 0.9,
      "events": [
        {
          "title": "Georgian Opposition Braces for New Jail Verdicts Amid Search for Broader Strategy",
          "translated_title": "Georgian Opposition Braces for New Jail Verdicts Amid Search for Broader Strategy",
          "link": "https://civil.ge/archives/744437",
          "date": "Mon, 20 Jul 2026 14:56:29 +0000",
          "source_country": "Georgia",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "Opposition awaits jail verdicts",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "დანიშვნიდან 10 თვის შემდეგ, ალექსანდრე კარტოზია გერმანიაში ელჩის აკრედიტაციას მიიღებს",
          "translated_title": null,
          "link": "https://netgazeti.ge/news/812152/",
          "date": "Mon, 20 Jul 2026 14:47:43 +0000",
          "source_country": "Georgia",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "Ambassador accreditation in Germany",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Man Arrested After Hitting Woman — Foreign National — in Kakheti Hotel Wedding Incident",
          "translated_title": null,
          "link": "https://civil.ge/archives/745025",
          "date": "Sun, 19 Jul 2026 15:15:03 +0000",
          "source_country": "Georgia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "Arrest over hotel wedding assault",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "რა უძღოდა წინ დაპირისპირებას – სასტუმრო „აგარანის მამული“ მორიგ განცხადებას ავრცელებს",
          "translated_title": null,
          "link": "https://netgazeti.ge/news/812142/",
          "date": "Mon, 20 Jul 2026 14:00:27 +0000",
          "source_country": "Georgia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "Hotel issues statement on confrontation",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Georgia’s Foreign Trade Up 5.8% in January-June 2026",
          "translated_title": null,
          "link": "https://civil.ge/archives/745091",
          "date": "Mon, 20 Jul 2026 08:23:31 +0000",
          "source_country": "Georgia",
          "category": "trade_agreement",
          "weight": -2.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "Foreign trade increase",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        }
      ]
    },
    "Greece": {
      "index": 1.0,
      "raw_score": 0.0,
      "events": []
    },
    "Iran": {
      "index": 8.44,
      "raw_score": 7.31,
      "events": [
        {
          "title": "Ιρανικά ΜΜΕ: «Eχθρική αεροπορική επιδρομή» στο Σιράζ",
          "translated_title": "Ιρανικά ΜΜΕ: «Eχθρική αεροπορική επιδρομή» στο Σιράζ",
          "link": "https://www.naftemporiki.gr/kosmos/2140244/iranika-mme-echthriki-aeroporiki-epidromi-sto-siraz/?utm_source=rss&utm_medium=rss&utm_campaign=iranika-mme-echthriki-aeroporiki-epidromi-sto-siraz",
          "date": "Mon, 20 Jul 2026 15:34:27 +0000",
          "source_country": "Greece",
          "category": "military_conflict",
          "weight": 8.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "Hostile airstrike on Shiraz",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Trump says US strikes hit Iran in 'honour' of American soldiers killed",
          "translated_title": "Trump says US strikes hit Iran in 'honour' of American soldiers killed",
          "link": "https://www.bbc.co.uk/news/articles/cly52xzjd3qo?at_medium=RSS&at_campaign=rss",
          "date": "Mon, 20 Jul 2026 11:18:40 GMT",
          "source_country": "Iran",
          "category": "military_conflict",
          "weight": 8.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "US strikes on Iran",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "US strikes hit Iran for seventh consecutive night",
          "translated_title": "US strikes hit Iran for seventh consecutive night",
          "link": "https://www.bbc.co.uk/news/articles/cy748n8zx8ro?at_medium=RSS&at_campaign=rss",
          "date": "Sat, 18 Jul 2026 17:44:56 GMT",
          "source_country": "Iran",
          "category": "military_conflict",
          "weight": 8.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "US strikes on Iran",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Iranian official reports US attack on Shiraz",
          "translated_title": "Iranian official reports US attack on Shiraz",
          "link": "https://www.middleeasteye.net/live-blog/live-blog-update/iranian-official-reports-us-attack-shiraz",
          "date": "Mon, 20 Jul 2026 16:34:11 +0100",
          "source_country": "Iran",
          "category": "military_conflict",
          "weight": 8.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "US attack on Shiraz",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Iran ready to 'welcome' US ground invasion as tit-for-tat attacks continue",
          "translated_title": "Iran ready to 'welcome' US ground invasion as tit-for-tat attacks continue",
          "link": "https://www.middleeasteye.net/live-blog/live-blog-update/iran-ready-welcome-us-ground-invasion-tit-tat-attacks-continue",
          "date": "Mon, 20 Jul 2026 16:00:52 +0100",
          "source_country": "Iran",
          "category": "military_conflict",
          "weight": 8.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "Iran-US attack escalation",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Explosion heard in Shiraz, Fars news agency reports",
          "translated_title": "Explosion heard in Shiraz, Fars news agency reports",
          "link": "https://www.middleeasteye.net/live-blog/live-blog-update/explosion-heard-shiraz-fars-news-agency-reports",
          "date": "Mon, 20 Jul 2026 15:57:16 +0100",
          "source_country": "Iran",
          "category": "military_conflict",
          "weight": 8.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "Explosion in Shiraz",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Iran ready to 'welcome' US ground invasion as tit-for-tat attacks continue",
          "translated_title": "Iran ready to 'welcome' US ground invasion as tit-for-tat attacks continue",
          "link": "https://www.middleeasteye.net/news/iran-ready-to-welcome-us-ground-invasion-tit-for-tat-attacks",
          "date": "Mon, 20 Jul 2026 14:52:51 +0100",
          "source_country": "Iran",
          "category": "military_conflict",
          "weight": 8.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "Iran-US attack escalation",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "France warns of consequences after Iranian security services detain embassy staff",
          "translated_title": null,
          "link": "https://www.middleeasteye.net/live-blog/live-blog-update/france-warns-consequences-after-iranian-security-services-detain-embassy",
          "date": "Mon, 20 Jul 2026 16:46:45 +0100",
          "source_country": "Iran",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "France warns over detained embassy staff",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        }
      ]
    },
    "Iraq": {
      "index": 5.06,
      "raw_score": 2.5,
      "events": [
        {
          "title": "US soldier killed and one injured after Iranian attack in Iraq",
          "translated_title": "US soldier killed and one injured after Iranian attack in Iraq",
          "link": "https://www.bbc.co.uk/news/articles/cgk417jp83po?at_medium=RSS&at_campaign=rss",
          "date": "Sun, 19 Jul 2026 19:45:12 GMT",
          "source_country": "Iran",
          "category": "terrorism",
          "weight": 7.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Iraq",
          "llm_final_country": "Iraq",
          "llm_subject": "US soldier killed in Iranian attack in Iraq",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Iraq turns to Syria to bypass the Strait of Hormuz blockade - The New Arab",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMidEFVX3lxTE5tNWFKalBETGdUVlVQUmVScGhCMmJBVEdTNFRFUWFaN3BzYnNjTngtR0J0MURYUmdEeUFmbjFWVzlLd1c5Rm1YQXZxOVI5RGU5SnNLTzNvNzFkOVhXMm5kcGdUeHBscjdiV0VFekw4V1JlWDBV0gF6QVVfeXFMT1BrY3RuWUpOQkYwNG92QTZQRHRkdVZjNU9NZ0pxM1JiMHd3WkF3aDBsUTFZLWlfQmx6Z0F6ZTZFUzNjT3ZuanJGRTdqSFZIVmtPSWwtc0R4S1l2OXBKQlltczNTSk44bU9jSVhaMGdqUUlPRVByaU9GZWc?oc=5",
          "date": "Sun, 19 Jul 2026 07:00:00 GMT",
          "source_country": "Syria",
          "category": "trade_agreement",
          "weight": -2.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Iraq",
          "llm_final_country": "Iraq",
          "llm_subject": "Iraq uses Syria to bypass Hormuz",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        }
      ]
    },
    "Syria": {
      "index": 4.76,
      "raw_score": 2.25,
      "events": [
        {
          "title": "Syria’s leader charms the world, crushes the Druze. Israel should be wary - The Times of Israel",
          "translated_title": "Syria’s leader charms the world, crushes the Druze. Israel should be wary - The Times of Israel",
          "link": "https://news.google.com/rss/articles/CBMipgFBVV95cUxPVkw4bWpGbWZEbExiVV9xcWdBNnRPLTd2d1J4V2dXYTFxMXM1UnhkR2IwdDg4VUo1R040S2hYMlFidkZsT0ZSbmVmcERuOFFQSEpKWDA2MG1lVURSaVVYaWRQY2ZKZWs1Y0w3WUpQSW1WZmx6clliQUl2NlV5RXlmMHlMSFZFSUJFdFRHYmF4eDEwVEU5eUFwTzFFREhTWEJqSDZnaDFR?oc=5",
          "date": "Sun, 19 Jul 2026 11:09:00 GMT",
          "source_country": "Syria",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Syria leader repression of Druze",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syria’s New Security Appointments: Strategic Implications for Stability and State Consolidation",
          "translated_title": "Syria’s New Security Appointments: Strategic Implications for Stability and State Consolidation",
          "link": "https://syrianobserver.com/syrian-actors/syrias-new-security-appointments-strategic-implications-for-stability-and-state-consolidation.html",
          "date": "Mon, 20 Jul 2026 08:27:02 +0000",
          "source_country": "Syria",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Syria security appointments",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syrian Citizenship Is the State’s Foundation; The Democratic Option Has Not Been on the Table for Years: Azmi Bishara",
          "translated_title": "Syrian Citizenship Is the State’s Foundation; The Democratic Option Has Not Been on the Table for Years: Azmi Bishara",
          "link": "https://syrianobserver.com/syrian-actors/syrian-citizenship-is-the-states-foundation-the-democratic-option-has-not-been-on-the-table-for-years-azmi-bishara.html",
          "date": "Sun, 19 Jul 2026 21:02:30 +0000",
          "source_country": "Syria",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Syrian citizenship and democracy",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syria’s Al-Sharaa reshuffles security and intelligence leadership - Al Jazeera",
          "translated_title": "Syria’s Al-Sharaa reshuffles security and intelligence leadership - Al Jazeera",
          "link": "https://news.google.com/rss/articles/CBMiqAFBVV95cUxONkZzVUVhWi1aS0s0eS1TcGJtQXdQejRWbjlreE54dFpvX0R0RmdWYzNON3lidGx3Mk5QTjBZWExqUTNNR21MS2MtTGNRRUpMTksyaXFpb2NxQU4wV2tBYlB3VjZDaGoxZjdEaDluUjZrRjUybjdSZ1VmYXVZVEFMa2FpcUVfNXZ1OHlJTEo2Ulp5Vy1JOHVWdEY1LV9aSGVzSjVfX2o5RGbSAa4BQVVfeXFMTnpiUUdVam5yUjgzZzJNX0JfOW10bnVuVmpUMXRrSWtnXzFiMTloX2pPVWlKTzhZMm9pYXdhUmZSODJFaXVTeGZkdFIxMmlGbHJhbFk4Uk9qVkJHWkNwdUFabFoyLVd0LUZ2b2xrYXRoeXRJci1MVGkwZ2NsNmpxQkpuQzN4ZkI3d3ZsemNJbFJrNElyOTZlUThaZFA0QUZ4bXBHTEVhams4b1lEbWR3?oc=5",
          "date": "Sun, 19 Jul 2026 16:59:05 GMT",
          "source_country": "Syria",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Al-Sharaa reshuffles security leadership",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syria's Kurds hold 12 parliamentary seats, deserve 30 - Shafaq News | Latest breaking news in Iraq and the world - شفق نيوز",
          "translated_title": "Syria's Kurds hold 12 parliamentary seats, deserve 30 - Shafaq News | Latest breaking news in Iraq and the world - شفق نيوز",
          "link": "https://news.google.com/rss/articles/CBMijgFBVV95cUxOcVQyMzFCV3RmbkZySUlFS2Q5ZUhEOXFrckpkVldJVENERVk5LXpydEFaY0xlTHZLVWljejF2WUFqMk40dm8zMFdLUzhPR1g3VEdFWFJ5Q3NMQ29FQ2hYSHlicmJoV0xTbzBrTlRSeG1NQnpBTFVyRGdyamxjNlM3ZXlkaVA1WHI3WUpTTW1R?oc=5",
          "date": "Sun, 19 Jul 2026 20:39:16 GMT",
          "source_country": "Syria",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Syrian Kurds parliamentary seats",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Decade of conflict: Scars of war linger on Syria's Saint Simeon monastery - RTL Today",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMimwFBVV95cUxObW1DNU41NS1JSWkwWk5OdFVmMGtxLUo2Qm1tdFZSZm9ZckY2dlZyeWxiQmlEcDdMaUl5UGJSQ09icllkZ3NmNVZ3VUJ3MGMwM1hjTkNXdXNhSXFqNFlHT3dEM3dQb2N0NnZuNjdlY2lyZ044UXp4dGQ5OGpWeFNja1B2dmt4VFJWd3BwSE9pQ3Q3MGhqQnVZUkVxMA?oc=5",
          "date": "Mon, 20 Jul 2026 13:21:39 GMT",
          "source_country": "Syria",
          "category": "humanitarian_crisis",
          "weight": 3.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Syria war scars on monastery",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Basit Kareem Iqbal, The Dread Heights: Tribulation and Refuge after the Syrian Revolution (New Texts Out Now) - Jadaliyya",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMi3wFBVV95cUxPX25VNXMwaWdiT3dRM0NEWUVKTVRUVzU2QWtFTlduM2xzdklqekQ5cnVXM2ZLX0JyVzNVbUZGNjlBYndJTURsOEltRkxKYlFFSVp2b3FWZFBWNk1DQjAyTXlNMUJjYmpIeG1sWUdGMlJIZ1QxTFQyWGdxaWgwN3lSSjc4NzcweDFQc3BGaUhMV3BSNHR0VXo3LWNxcUkyTGtiQlZ0c2wtT1Rtd0FQVENUVTgyRm9LUElYRDZZeHRPdmQ0c3JiWEZBVGU0ODM0YmloaWpBMjMxLXA2TzdoRU1r?oc=5",
          "date": "Mon, 20 Jul 2026 14:36:07 GMT",
          "source_country": "Syria",
          "category": "humanitarian_crisis",
          "weight": 3.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Refuge after Syrian revolution",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Foreign Ministry: Azerbaijan repatriates 16 more citizens from Syria - AZƏRTAC",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMipgFBVV95cUxObndQVzM5QXZ0WlRzSlZ5N295dkVNdFZRNUtlZzF4U3ZLTS1pelNSbTJKUS1rWjFzWVZHeGRkazZob19vaVh2VlpVZk5kaWJ2OUdBR05Rc3ZrOHZfWTVTbW4wQzRRZzhuMl82SEZuSGRRSlZmY3NGWUUxQjdqbzZpY2ZrcHUzVGVNQ3lNTXFiWHd2Z0F4RlR3eUVmeXZ2Sy1tbENscGp3?oc=5",
          "date": "Mon, 20 Jul 2026 14:54:00 GMT",
          "source_country": "Syria",
          "category": "humanitarian_crisis",
          "weight": 3.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Azerbaijan repatriates citizens from Syria",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "After Macron’s Vows to Revive Christian Schools, Aleppo Bids Farewell to the Franciscan Sisters",
          "translated_title": null,
          "link": "https://syrianobserver.com/society/after-macrons-vows-to-revive-christian-schools-aleppo-bids-farewell-to-the-franciscan-sisters.html",
          "date": "Sun, 19 Jul 2026 21:01:20 +0000",
          "source_country": "Syria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Aleppo Franciscan Sisters departure",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Scars of war linger on Syria's Saint Simeon monastery - KMVU FOX 26 Medford",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMi3gFBVV95cUxNaGVKemt1bXp5NmRTRHpWODB2VlZyWE5kVTI4SDFDQWF5UGFNaWgtZm1QWkdScHJDSHZ6aXFZVUtpNDlSVlRvNVg5SWNoMFU3ZzUxclNZRkEzMUwzVld5SG1hOTJNeGxQN1QwTl9hQUl3bTFNeFV6MVVXamU2TlB2WldKbGtwQkR1cG93M1JyTjBEOXQ2RHNLTGhhU3JrRElxd2ltNDlQVGNIWWJvOGlvWHkwbm9aRS1uUGFfdXAzcXB0akQwUDRaZjhrWGV2U05GWFFIS09pc2ZSSTZoSUE?oc=5",
          "date": "Mon, 20 Jul 2026 14:20:35 GMT",
          "source_country": "Syria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "War scars at Saint Simeon monastery",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "When the circle of loyalty narrows, the circle of danger widens. - تيار المستقبل السوري",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMimwFBVV95cUxQVUtGUk9VcE01QXVRSjdMQzhRdGFEb3QwdFVWUUQyN3E0OHVyU25fT0hnNWdMVXB5VEpoYktRQWQ0YlJNQ0ZCZFcxc19uS1pRM1J2V1dJaDlWT0g3OVMwZDdocFpCM19LR1BmUF9DYXc2TDZibFR1cmM3Z3JNWDR1empYelU5NXFfQzNfZGlBRWVEOVMyaUxFM3AwWQ?oc=5",
          "date": "Mon, 20 Jul 2026 05:26:25 GMT",
          "source_country": "Syria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Comment on loyalty and danger",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syria at the Forefront of the Region’s Emerging Transit Map",
          "translated_title": null,
          "link": "https://syrianobserver.com/syrian-actors/syria-at-the-forefront-of-the-regions-emerging-transit-map.html",
          "date": "Sun, 19 Jul 2026 21:02:03 +0000",
          "source_country": "Syria",
          "category": "trade_agreement",
          "weight": -2.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Syria regional transit map",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Syria"
        }
      ]
    },
    "Bulgaria": {
      "index": 1.0,
      "raw_score": 0.0,
      "events": []
    }
  },
  "history": [
    {
      "timestamp": "2026-07-18T16:54:33.573101",
      "main_index": 5.81,
      "index": 5.81,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-18T18:58:51.630070",
      "main_index": 5.77,
      "index": 5.77,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-18T20:45:48.154297",
      "main_index": 5.29,
      "index": 5.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-18T22:48:34.666710",
      "main_index": 4.55,
      "index": 4.55,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-19T02:09:10.129893",
      "main_index": 5.78,
      "index": 5.78,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-19T06:29:30.847607",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-19T09:53:37.211786",
      "main_index": 4.44,
      "index": 4.44,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-19T11:12:26.345119",
      "main_index": 5.99,
      "index": 5.99,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-19T13:09:56.000224",
      "main_index": 4.4,
      "index": 4.4,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-19T14:55:15.143449",
      "main_index": 4.38,
      "index": 4.38,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-19T16:55:49.559847",
      "main_index": 3.44,
      "index": 3.44,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-19T19:04:08.585322",
      "main_index": 3.75,
      "index": 3.75,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-19T20:45:57.663505",
      "main_index": 4.55,
      "index": 4.55,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-19T22:49:55.759980",
      "main_index": 4.02,
      "index": 4.02,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-20T02:33:51.069079",
      "main_index": 4.03,
      "index": 4.03,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-20T06:46:38.787296",
      "main_index": 4.6,
      "index": 4.6,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-20T13:59:13.169198",
      "main_index": 3.89,
      "index": 3.89,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-20T15:52:32.740559",
      "main_index": 4.17,
      "index": 4.17,
      "type": "historical"
    }
  ],
  "forecast": [
    {
      "timestamp": "2026-07-20T16:52:32.740559",
      "index": 3.64,
      "main_index": 3.64,
      "confidence": 0.39,
      "type": "forecast"
    },
    {
      "timestamp": "2026-07-20T17:52:32.740559",
      "index": 3.52,
      "main_index": 3.52,
      "confidence": 0.35,
      "type": "forecast"
    },
    {
      "timestamp": "2026-07-20T18:52:32.740559",
      "index": 3.4,
      "main_index": 3.4,
      "confidence": 0.32,
      "type": "forecast"
    },
    {
      "timestamp": "2026-07-20T19:52:32.740559",
      "index": 3.28,
      "main_index": 3.28,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-07-20T20:52:32.740559",
      "index": 3.16,
      "main_index": 3.16,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-07-20T21:52:32.740559",
      "index": 3.04,
      "main_index": 3.04,
      "confidence": 0.3,
      "type": "forecast"
    }
  ],
  "methodology": {
    "name": "LLM Border Threat Taxonomy",
    "description": "OpenRouter free routing chooses the final country attribution and canonical threat category for each headline.",
    "weights": {
      "military_conflict": 8.0,
      "terrorism": 7.0,
      "border_security": 5.0,
      "political_instability": 4.0,
      "humanitarian_crisis": 3.0,
      "diplomatic_tensions": 2.5,
      "trade_agreement": -2.0,
      "neutral": 0.0
    },
    "formula": "PerCountry = 1 + 9*(1 - exp(-avg(weight)/5 * 1.2)); Composite = weighted_avg(PerCountry)",
    "scale": {
      "min": 1.0,
      "max": 10.0,
      "thresholds": {
        "STABLE": [
          1.0,
          4.0
        ],
        "ELEVATED": [
          4.0,
          7.0
        ],
        "CRITICAL": [
          7.0,
          10.0
        ]
      }
    }
  },
  "briefing": {
    "regional_summary_6h": {
      "slot_start": "2026-07-20T06:00:00Z",
      "slot_end": "2026-07-20T12:00:00Z",
      "generated_at": "2026-07-20T13:59:04Z",
      "next_refresh_at": "2026-07-20T18:00:00Z",
      "window_hours": 6,
      "source_event_count": 4,
      "source_countries": [
        "Armenia",
        "Iran",
        "Syria"
      ],
      "headline": "Iran military conflict dominates border environment with US strikes and Gulf bombing",
      "bullets": [
        "Iran conducted bombing operations against Gulf states while avoiding US naval assets and Israel.",
        "US strikes hit Iran in relation to American soldiers killed, per Trump.",
        "Syria announced new security appointments with implications for state consolidation."
      ],
      "watch": "Monitor Iran military conflict escalation near Turkiye's southern border."
    }
  }
};