window.BNTI_DATA = {
  "meta": {
    "generated_at": "2026-07-29T02:08:36.092809",
    "main_index": 5.57,
    "status": "ELEVATED",
    "active_scan": false,
    "next_update": "2026-07-29T04:00:00",
    "version": "2.0.0"
  },
  "countries": {
    "Armenia": {
      "index": 1.21,
      "raw_score": 0.1,
      "events": [
        {
          "title": "Pashinyan Urges Putin to Remove Restrictions on Armenian Exports",
          "translated_title": null,
          "link": "https://hetq.am/en/article/182909",
          "date": "Mon, 27 Jul 2026 19:40:00 +0400",
          "source_country": "Armenia",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Armenian export restrictions negotiation",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Yerevan’s COP-17 Botched Preparations: Construction Waste Tumbling Into Hrazdan Gorge",
          "translated_title": null,
          "link": "https://hetq.am/en/article/182896",
          "date": "Mon, 27 Jul 2026 21:33:00 +0400",
          "source_country": "Armenia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Construction waste management in Yerevan",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Armenia, ADB assess progress on North–South road corridor and tunnel projects",
          "translated_title": null,
          "link": "https://en.armradio.am/2026/07/28/armenia-adb-assess-progress-on-north-south-road-corridor-and-tunnel-projects/",
          "date": "Tue, 28 Jul 2026 14:09:45 +0000",
          "source_country": "Armenia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "North-South road corridor development",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Armenian Security Council Secretary receives outgoing French Ambassador",
          "translated_title": null,
          "link": "https://en.armradio.am/2026/07/28/armenian-security-council-secretary-receives-outgoing-french-ambassador/",
          "date": "Tue, 28 Jul 2026 12:59:41 +0000",
          "source_country": "Armenia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Diplomatic reception of French Ambassador",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Turkey takes practical steps to restore rail link with Armenia",
          "translated_title": null,
          "link": "https://jam-news.net/turkey-restores-akyaka-gyumri-railway/",
          "date": "Tue, 28 Jul 2026 18:03:17 +0000",
          "source_country": "Georgia",
          "category": "trade_agreement",
          "weight": -2.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Turkey-Armenia rail link restoration",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        }
      ]
    },
    "Georgia": {
      "index": 5.22,
      "raw_score": 2.64,
      "events": [
        {
          "title": "U.S. Embassy ‘Troubled’ Over Georgian Government’s ‘Hate Speech’ Division, Warns Against Restrictions on Free Speech",
          "translated_title": "U.S. Embassy ‘Troubled’ Over Georgian Government’s ‘Hate Speech’ Division, Warns Against Restrictions on Free Speech",
          "link": "https://civil.ge/archives/746205",
          "date": "Tue, 28 Jul 2026 08:55:18 +0000",
          "source_country": "Georgia",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "Government hate speech policies",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Illegally Detained Georgian Citizen Released From Tskhinvali Custody",
          "translated_title": "Illegally Detained Georgian Citizen Released From Tskhinvali Custody",
          "link": "https://civil.ge/archives/746106",
          "date": "Mon, 27 Jul 2026 10:54:40 +0000",
          "source_country": "Georgia",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "Release of detained Georgian citizen from Tskhinvali custody",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "MMA Fighter Launches Movement to Defend Georgian ‘Values and Traditions,’ Fight ‘Pseudo-Liberal,’ ‘Foreign-Funded’ Groups",
          "translated_title": "MMA Fighter Launches Movement to Defend Georgian ‘Values and Traditions,’ Fight ‘Pseudo-Liberal,’ ‘Foreign-Funded’ Groups",
          "link": "https://civil.ge/archives/746068",
          "date": "Mon, 27 Jul 2026 10:22:33 +0000",
          "source_country": "Georgia",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "MMA fighter's movement against perceived liberal and foreign-funded groups",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Georgia Launches Case Against Four Foreign Nationals, Five Entities Over Alleged Money Laundering Scheme",
          "translated_title": "Georgia Launches Case Against Four Foreign Nationals, Five Entities Over Alleged Money Laundering Scheme",
          "link": "https://civil.ge/archives/746020",
          "date": "Mon, 27 Jul 2026 08:50:59 +0000",
          "source_country": "Georgia",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "Georgia's case against foreign nationals and entities over money laundering",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Opinion from Tbilisi: ‘Dictator wants to be liked by everyone. Those who don’t like him must be neutralised’",
          "translated_title": null,
          "link": "https://jam-news.net/opinion-from-tbilisi-dictator-wants-to-be-liked-by-everyone-those-who-dont-like-him-must-be-neutralised/",
          "date": "Tue, 28 Jul 2026 17:14:37 +0000",
          "source_country": "Georgia",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "Georgian political repression concerns",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "US Embassy expresses concern over creation of Georgia’s hate speech unit",
          "translated_title": null,
          "link": "https://jam-news.net/us-embassy-expresses-concern-over-creation-of-georgias-hate-speech-unit/",
          "date": "Tue, 28 Jul 2026 15:36:33 +0000",
          "source_country": "Georgia",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "US concern over Georgia hate speech unit",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Papuashvili Questions EU Membership Benefits If Unanimity in Decision-Making Is Abolished",
          "translated_title": null,
          "link": "https://civil.ge/archives/746157",
          "date": "Mon, 27 Jul 2026 14:52:58 +0000",
          "source_country": "Georgia",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "EU membership decision-making reforms",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "EU Sanctions Include Inter RAO, Russian Energy Giant Indirectly Owning Georgia’s Power Assets",
          "translated_title": null,
          "link": "https://civil.ge/archives/746074",
          "date": "Mon, 27 Jul 2026 11:38:13 +0000",
          "source_country": "Georgia",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "EU sanctions on Russian energy entities affecting Georgia's power assets",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Georgian Dream Culture Minister Tinatin Rukhadze Resigns, Citing Health Reasons",
          "translated_title": null,
          "link": "https://civil.ge/archives/746277",
          "date": "Tue, 28 Jul 2026 14:53:02 +0000",
          "source_country": "Georgia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "Cultural minister resignation",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "‘Rike Tubes,’ UNM-Era Modern Structures That Never Opened, Being Demolished in Tbilisi",
          "translated_title": null,
          "link": "https://civil.ge/archives/746257",
          "date": "Tue, 28 Jul 2026 13:56:35 +0000",
          "source_country": "Georgia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "Demolition of unused infrastructure in Tbilisi",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "SSSG Arrests Former Law Enforcement Employee Accused of Fraud Over Promises to Secure Defendants’ Release",
          "translated_title": null,
          "link": "https://civil.ge/archives/746121",
          "date": "Mon, 27 Jul 2026 12:15:01 +0000",
          "source_country": "Georgia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "Arrest for law enforcement fraud",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        }
      ]
    },
    "Greece": {
      "index": 1.0,
      "raw_score": 0.0,
      "events": []
    },
    "Iran": {
      "index": 7.29,
      "raw_score": 5.0,
      "events": [
        {
          "title": "Ο στρατός των ΗΠΑ λέει πως αναχαίτισε πυραύλους που εκτοξεύτηκαν από το Ιράν",
          "translated_title": "Ο στρατός των ΗΠΑ λέει πως αναχαίτισε πυραύλους που εκτοξεύτηκαν από το Ιράν",
          "link": "https://www.protothema.gr/world/article/1857462/o-stratos-ton-ipa-leei-pos-anahaitise-puraulous-pou-ektoxeutikan-apo-to-iran/?utm_source=rss",
          "date": "Wed, 29 Jul 2026 03:28:19 +0300",
          "source_country": "Greece",
          "category": "military_conflict",
          "weight": 8.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "US military intercepts Iranian missiles",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "As the US pauses the war with Iran, is Trump really running out of weapons?",
          "translated_title": "As the US pauses the war with Iran, is Trump really running out of weapons?",
          "link": "https://www.bbc.co.uk/news/articles/c0qvnk2ezp7o?at_medium=RSS&at_campaign=rss",
          "date": "Mon, 27 Jul 2026 21:06:42 GMT",
          "source_country": "Iran",
          "category": "military_conflict",
          "weight": 8.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "US military weapon supplies in Iran war",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "More than 600 US military service members injured since Iran War began in February",
          "translated_title": "More than 600 US military service members injured since Iran War began in February",
          "link": "https://www.bbc.co.uk/news/articles/c998pzd1e8xo?at_medium=RSS&at_campaign=rss",
          "date": "Mon, 27 Jul 2026 13:31:57 GMT",
          "source_country": "Iran",
          "category": "military_conflict",
          "weight": 8.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "US military casualties in Iran war",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Ukraine dismisses Iranian threats as Caspian Sea strike directly links wars",
          "translated_title": "Ukraine dismisses Iranian threats as Caspian Sea strike directly links wars",
          "link": "https://www.bbc.co.uk/news/articles/cwyj7yl0xndo?at_medium=RSS&at_campaign=rss",
          "date": "Mon, 27 Jul 2026 16:33:05 GMT",
          "source_country": "Iran",
          "category": "military_conflict",
          "weight": 8.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "Iranian threats and Caspian Sea strikes",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "US military says Iran launched ballistic missile attack",
          "translated_title": "US military says Iran launched ballistic missile attack",
          "link": "https://www.newarab.com/news/us-military-says-iran-launched-ballistic-missile-attack",
          "date": "Tue, 28 Jul 2026 15:44:22 +0100",
          "source_country": "Iraq",
          "category": "military_conflict",
          "weight": 8.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "Iranian ballistic missile attack",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Trump says Iran war talks taking place during lull in strikes",
          "translated_title": null,
          "link": "https://www.bbc.co.uk/news/articles/c62xn4vzmnpo?at_medium=RSS&at_campaign=rss",
          "date": "Mon, 27 Jul 2026 21:10:56 GMT",
          "source_country": "Iran",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "Iran war talks during strike lull",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "US and Iran pause strikes for third night to make space for talks, US ambassador says",
          "translated_title": null,
          "link": "https://www.bbc.co.uk/news/articles/c5y45kdkynpo?at_medium=RSS&at_campaign=rss",
          "date": "Mon, 27 Jul 2026 08:14:46 GMT",
          "source_country": "Iran",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "Pause in US-Iran strikes for talks",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Gulf states back Omani plan for voluntary Iran transit fees in Strait of Hormuz, source",
          "translated_title": null,
          "link": "https://sana.sy/en/middle-east/2332710/",
          "date": "Tue, 28 Jul 2026 12:33:25 +0000",
          "source_country": "Syria",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "Gulf states support Iran transit fees plan",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Тръмп и Нетаняху се срещат за първи път след началото на войната срещу Иран",
          "translated_title": null,
          "link": "https://www.dnevnik.bg/sviat/2026/07/28/4940271_trump_i_netaniahu_se_sreshtat_za_purvi_put_sled/?ref=rss",
          "date": "Tue, 28 Jul 2026 19:31:00 +0300",
          "source_country": "Bulgaria",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "Trump and Netanyahu meet for the first time since the start of the war against Iran",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Oil price dives as US and Iran pause attacks",
          "translated_title": null,
          "link": "https://www.bbc.co.uk/news/articles/clyj834jn5lo?at_medium=RSS&at_campaign=rss",
          "date": "Mon, 27 Jul 2026 15:08:37 GMT",
          "source_country": "Iran",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "Oil price drop amid US-Iran pause",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        }
      ]
    },
    "Iraq": {
      "index": 8.68,
      "raw_score": 8.0,
      "events": [
        {
          "title": "Σαουδική Αραβία και ΗΠΑ βομβάρδισαν φιλοϊρανικές πολιτοφυλακές στο Ιράκ μετά τις επιθέσεις με drones",
          "translated_title": "Σαουδική Αραβία και ΗΠΑ βομβάρδισαν φιλοϊρανικές πολιτοφυλακές στο Ιράκ μετά τις επιθέσεις με drones",
          "link": "https://www.protothema.gr/world/article/1857467/saoudiki-aravia-kai-ipa-vomvardisan-filoiranikes-politofulakes-sto-irak-meta-tis-epitheseis-me-drones/?utm_source=rss",
          "date": "Wed, 29 Jul 2026 04:31:47 +0300",
          "source_country": "Greece",
          "category": "military_conflict",
          "weight": 8.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Iraq",
          "llm_final_country": "Iraq",
          "llm_subject": "US and Saudi strikes on pro-Iran militias in Iraq",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Iraq"
        }
      ]
    },
    "Syria": {
      "index": 6.51,
      "raw_score": 3.95,
      "events": [
        {
          "title": "Syrian Security Forces Conduct Major Operations Against Militants in Jableh and ISIS Cells in Aleppo",
          "translated_title": "Syrian Security Forces Conduct Major Operations Against Militants in Jableh and ISIS Cells in Aleppo",
          "link": "https://syrianobserver.com/security/syrian-security-forces-conduct-major-operations-against-militants-in-jableh-and-isis-cells-in-aleppo.html",
          "date": "Tue, 28 Jul 2026 19:49:48 +0000",
          "source_country": "Syria",
          "category": "military_conflict",
          "weight": 8.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Military operations against militants in Jableh and Aleppo",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Israeli occupation forces carry out new incursion into western Daraa countryside",
          "translated_title": "Israeli occupation forces carry out new incursion into western Daraa countryside",
          "link": "https://sana.sy/en/syria/2332729/",
          "date": "Tue, 28 Jul 2026 14:06:35 +0000",
          "source_country": "Syria",
          "category": "military_conflict",
          "weight": 8.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Israeli incursion into Daraa countryside",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Woman Killed, Son Critically Injured in Sectarian Shooting in Homs",
          "translated_title": "Woman Killed, Son Critically Injured in Sectarian Shooting in Homs",
          "link": "https://syrianobserver.com/syrian-actors/woman-killed-son-critically-injured-in-sectarian-shooting-in-homs.html",
          "date": "Mon, 27 Jul 2026 21:00:03 +0000",
          "source_country": "Syria",
          "category": "terrorism",
          "weight": 7.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Sectarian shooting in Homs",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syria arrests ISIS members, seizes weapons in Aleppo - Anadolu Ajansı",
          "translated_title": "Syria arrests ISIS members, seizes weapons in Aleppo - Anadolu Ajansı",
          "link": "https://news.google.com/rss/articles/CBMinAFBVV95cUxOTUZXWHdfdy1FalJ6YVQ1Q0ExbFZ4eUp5dHE1Yk5xMHdFYTFEcEkySDB6R1RTZVVBeGwwemdLZjlCSVIzR0NaX0NOQWRyMDV5YVhlWGJtTkR2ZkVMcTBmLVFyZDl5MnBRMHZ3QjdUck5adEFQOTdsOEdqSXN2QW9vQjZPcy1EbW9qLU9FemRVSWstRGNFYm5EYjFtY2g?oc=5",
          "date": "Tue, 28 Jul 2026 15:18:35 GMT",
          "source_country": "Syria",
          "category": "border_security",
          "weight": 5.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Syria seizes ISIS weapons in Aleppo",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syria says it seized 850,000 narcotic pills from Lebanon - L'Orient Today",
          "translated_title": "Syria says it seized 850,000 narcotic pills from Lebanon - L'Orient Today",
          "link": "https://news.google.com/rss/articles/CBMirAFBVV95cUxNOEppYWtsc1lhNFN1bS1WaldTVDlxWkRaMEpncXJicHNzdl8zYmtUVVV0NkFwV1YxNFBjU090RXpsMXVTTlVjeHlpNjRMMThtdWVFNmZFTTlqbTg4M3ZjaGM4ZUY4QVc0MHJCd1U1bWdETW1YS002OVB0d3paZ1JXNld6eW0xYU1KNE5mWFdudjE2NnRJSU9LbFlaOUR0WkhBVTVJWWtoSjZoLXJf?oc=5",
          "date": "Mon, 27 Jul 2026 16:04:35 GMT",
          "source_country": "Syria",
          "category": "border_security",
          "weight": 5.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Syria seizes narcotics from Lebanon",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "The Syrian Jazira as the Bedrock of an Inclusive National Project",
          "translated_title": null,
          "link": "https://syrianobserver.com/syrian-actors/the-syrian-jazira-as-the-bedrock-of-an-inclusive-national-project.html",
          "date": "Mon, 27 Jul 2026 21:02:54 +0000",
          "source_country": "Syria",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Syrian Jazira's role in national project",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Sharaa’s Interview: Is Democracy Losing its Appeal?",
          "translated_title": null,
          "link": "https://syrianobserver.com/syrian-actors/sharaas-interview-is-democracy-losing-its-appeal.html",
          "date": "Mon, 27 Jul 2026 21:01:23 +0000",
          "source_country": "Syria",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Democracy's appeal in Syria",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syrian Foreign Minister receives outgoing Omani ambassador",
          "translated_title": null,
          "link": "https://sana.sy/en/syria/2332727/",
          "date": "Tue, 28 Jul 2026 14:07:05 +0000",
          "source_country": "Syria",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Syrian Foreign Minister receives Omani ambassador",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syria, South Korea sign education grant, media cooperation agreements",
          "translated_title": null,
          "link": "https://sana.sy/en/politics/2332722/",
          "date": "Tue, 28 Jul 2026 13:47:16 +0000",
          "source_country": "Syria",
          "category": "trade_agreement",
          "weight": -2.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Education and media cooperation agreements with South Korea",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syria, Egypt discuss expanding economic ties, reviving joint business council",
          "translated_title": null,
          "link": "https://sana.sy/en/economic/2332713/",
          "date": "Tue, 28 Jul 2026 12:40:19 +0000",
          "source_country": "Syria",
          "category": "trade_agreement",
          "weight": -2.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Expanding economic ties with Egypt",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        }
      ]
    },
    "Bulgaria": {
      "index": 4.16,
      "raw_score": 1.8,
      "events": [
        {
          "title": "ГЕРБ едва ли ще издигне собствен партиен кандидат за президент, обяви Горанов",
          "translated_title": null,
          "link": "https://www.dnevnik.bg/politika/2026/07/28/4940314_gerb_edva_li_shte_izdigne_sobstven_partien_kandidat_za/?ref=rss",
          "date": "Tue, 28 Jul 2026 21:51:00 +0300",
          "source_country": "Bulgaria",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "GERB unlikely to nominate own presidential candidate",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Moscow’s Embassy in Bulgaria Launches Fundraiser for Russian Troops",
          "translated_title": null,
          "link": "https://balkaninsight.com/techresponses/moscows-embassy-in-bulgaria-launches-fundraiser-for-russian-troops/",
          "date": "Mon, 27 Jun 2022 16:19:43 +0000",
          "source_country": "Bulgaria",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "Russian embassy fundraiser for troops in Ukraine",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "'Those responsible must face the consequences': Iran warns Bulgaria - Euronews.com",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMizgFBVV95cUxPM0trdEJwSzlfUFdzdFJ5SkZIUFM0c3lkb25aNzlsNmlYeGxoNHl5b1lQMjRNRVUzaVh6d2tNeXk4ZjktV1BuZTlyNUpWMVV0RW5tT1h0QTlmOWlmMjVrTjBhaGczV3hhYkFpR19hbWVwYXFFSzd6VmdhVkJjbDhHUHFFcFdwa0Y0MFk5MHc0UVYzVnBEdE52YmxYYmU5Xzk3OExBRG5rQ0dRY0t6aG5kbHg1cmpqWUFmOXVwdXhXMmFyQTZ2ekctOHhKZzdzZw?oc=5",
          "date": "Mon, 27 Jul 2026 10:30:53 GMT",
          "source_country": "Bulgaria",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "Iran warns Bulgaria over unspecified issue",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Facebook Page Uploaded Misleading Picture of Bulgarian Battalion Fighting In Ukraine",
          "translated_title": null,
          "link": "https://balkaninsight.com/techresponses/facebook-page-uploaded-misleading-picture-of-bulgarian-battalion-fighting-in-ukraine/",
          "date": "Thu, 24 Mar 2022 09:39:36 +0000",
          "source_country": "Bulgaria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "Misleading photo of Bulgarian battalion in Ukraine",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Бивш шеф на \"Булгаргаз\" осъди прокуратурата да му плати обезщетение от над 10 хил. евро",
          "translated_title": null,
          "link": "https://www.dnevnik.bg/bulgaria/2026/07/28/4940332_bivsh_shef_na_bulgargaz_osudi_prokuraturata_da_mu/?ref=rss",
          "date": "Tue, 28 Jul 2026 23:33:00 +0300",
          "source_country": "Bulgaria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "Former BulgarGaz chief sues prosecutor for damages",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        }
      ]
    }
  },
  "history": [
    {
      "timestamp": "2026-07-27T02:22:40.360985",
      "main_index": 4.81,
      "index": 4.81,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-27T07:01:10.119769",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-27T11:17:28.457968",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-27T14:20:17.447112",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-27T17:41:57.180039",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-27T19:21:14.838720",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-27T21:08:48.372283",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-27T22:58:50.059226",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-28T02:03:40.406458",
      "main_index": 3.92,
      "index": 3.92,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-28T05:02:47.606887",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-28T08:25:58.742863",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-28T11:56:28.601235",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-28T13:52:09.728533",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-28T16:04:47.286522",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-28T17:43:56.875399",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-28T19:17:49.563432",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-28T21:06:32.428163",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-28T22:57:42.187179",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-07-29T02:08:36.091546",
      "main_index": 5.57,
      "index": 5.57,
      "type": "historical"
    }
  ],
  "forecast": [
    {
      "timestamp": "2026-07-29T03:08:36.091546",
      "index": 7.07,
      "main_index": 7.07,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-07-29T04:08:36.091546",
      "index": 7.09,
      "main_index": 7.09,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-07-29T05:08:36.091546",
      "index": 7.11,
      "main_index": 7.11,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-07-29T06:08:36.091546",
      "index": 7.12,
      "main_index": 7.12,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-07-29T07:08:36.091546",
      "index": 7.14,
      "main_index": 7.14,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-07-29T08:08:36.091546",
      "index": 7.16,
      "main_index": 7.16,
      "confidence": 0.3,
      "type": "forecast"
    }
  ],
  "methodology": {
    "name": "LLM Border Threat Taxonomy",
    "description": "OpenRouter free routing chooses the final country attribution and canonical threat category for each headline.",
    "weights": {
      "military_conflict": 8.0,
      "terrorism": 7.0,
      "border_security": 5.0,
      "political_instability": 4.0,
      "humanitarian_crisis": 3.0,
      "diplomatic_tensions": 2.5,
      "trade_agreement": -2.0,
      "neutral": 0.0
    },
    "formula": "PerCountry = 1 + 9*(1 - exp(-avg(weight)/5 * 1.2)); Composite = weighted_avg(PerCountry)",
    "scale": {
      "min": 1.0,
      "max": 10.0,
      "thresholds": {
        "STABLE": [
          1.0,
          4.0
        ],
        "ELEVATED": [
          4.0,
          7.0
        ],
        "CRITICAL": [
          7.0,
          10.0
        ]
      }
    }
  },
  "briefing": {
    "regional_summary_6h": {
      "slot_start": "2026-07-28T18:00:00Z",
      "slot_end": "2026-07-29T00:00:00Z",
      "generated_at": "2026-07-29T02:08:34Z",
      "next_refresh_at": "2026-07-29T06:00:00Z",
      "window_hours": 6,
      "source_event_count": 3,
      "source_countries": [
        "Bulgaria",
        "Iran",
        "Syria"
      ],
      "headline": "Syria's cross-border operations intensify, triggering regional diplomatic strain and border security pressure",
      "bullets": [
        "Syrian security forces launch major operations against militants in Jableh and ISIS cells in Aleppo",
        "Iranian diplomatic tensions rise as Trump and Netanyahu meet for the first time since the war against Iran began",
        "Bulgaria's political instability deepens as GERB struggles to nominate a presidential candidate"
      ],
      "watch": "Monitor cross-border militant activity and diplomatic fallout from Iran-Israel engagement"
    }
  }
};