window.BNTI_DATA = {
  "meta": {
    "generated_at": "2026-08-03T02:15:42.286441",
    "main_index": 4.69,
    "status": "ELEVATED",
    "active_scan": false,
    "next_update": "2026-08-03T04:00:00",
    "version": "2.0.0"
  },
  "countries": {
    "Armenia": {
      "index": 6.65,
      "raw_score": 4.12,
      "events": [
        {
          "title": "Marriott drops genocide-tourism package in ethnically cleansed Artsakh",
          "translated_title": "Marriott drops genocide-tourism package in ethnically cleansed Artsakh",
          "link": "https://armenianweekly.com/2026/08/02/marriott-drops-genocide-tourism-package-in-ethnically-cleansed-artsakh/",
          "date": "Sun, 02 Aug 2026 13:08:29 +0000",
          "source_country": "Armenia",
          "category": "border_security",
          "weight": 5.0,
          "confidence": 0.35,
          "ai_model": "deterministic-fallback",
          "ai_category": false,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Marriott drops genocide-tourism package in ethnically cleansed Artsakh",
          "llm_country_audit_corrected": false,
          "fallback_reason": "llm_attribution_failed",
          "ai_confidence_score": "35.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "International Backlash Forces Marriott to Drop Tourism Package in Ethnically Cleansed Artsakh",
          "translated_title": "International Backlash Forces Marriott to Drop Tourism Package in Ethnically Cleansed Artsakh",
          "link": "https://hetq.am/en/article/183021",
          "date": "Sun, 02 Aug 2026 18:54:00 +0400",
          "source_country": "Armenia",
          "category": "border_security",
          "weight": 5.0,
          "confidence": 0.35,
          "ai_model": "deterministic-fallback",
          "ai_category": false,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "International Backlash Forces Marriott to Drop Tourism Package in Ethnically Cleansed Artsakh",
          "llm_country_audit_corrected": false,
          "fallback_reason": "llm_attribution_failed",
          "ai_confidence_score": "35.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Pashinyan Reappointed Armenia’s Prime Minister",
          "translated_title": "Pashinyan Reappointed Armenia’s Prime Minister",
          "link": "https://hetq.am/en/article/183018",
          "date": "Sun, 02 Aug 2026 18:23:00 +0400",
          "source_country": "Armenia",
          "category": "border_security",
          "weight": 5.0,
          "confidence": 0.35,
          "ai_model": "deterministic-fallback",
          "ai_category": false,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Pashinyan Reappointed Armenia’s Prime Minister",
          "llm_country_audit_corrected": false,
          "fallback_reason": "llm_attribution_failed",
          "ai_confidence_score": "35.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Armenia’s New Parliament Convenes: Catholicos Karekin II Not Invited",
          "translated_title": "Armenia’s New Parliament Convenes: Catholicos Karekin II Not Invited",
          "link": "https://hetq.am/en/article/183019",
          "date": "Sun, 02 Aug 2026 15:30:00 +0400",
          "source_country": "Armenia",
          "category": "border_security",
          "weight": 5.0,
          "confidence": 0.35,
          "ai_model": "deterministic-fallback",
          "ai_category": false,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Armenia’s New Parliament Convenes: Catholicos Karekin II Not Invited",
          "llm_country_audit_corrected": false,
          "fallback_reason": "llm_attribution_failed",
          "ai_confidence_score": "35.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Van Ardi, One of Armenia’s Premier Boutique Estates, Launches Three New Wines and Wine Club",
          "translated_title": "Van Ardi, One of Armenia’s Premier Boutique Estates, Launches Three New Wines and Wine Club",
          "link": "https://hetq.am/en/article/183003",
          "date": "Sat, 01 Aug 2026 12:52:00 +0400",
          "source_country": "Armenia",
          "category": "border_security",
          "weight": 5.0,
          "confidence": 0.35,
          "ai_model": "deterministic-fallback",
          "ai_category": false,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Van Ardi, One of Armenia’s Premier Boutique Estates, Launches Three New Wines and Wine Club",
          "llm_country_audit_corrected": false,
          "fallback_reason": "llm_attribution_failed",
          "ai_confidence_score": "35.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Եկեղեցին պիտի շարունակի իր կարողություններով զորավիգ լինել հայոց պետությանը բոլոր բարի իրագործումներում․ Ամենայն Հայոց Կաթողիկոսն ընդունեց ԱԺ պատգամավորներին",
          "translated_title": "Եկեղեցին պիտի շարունակի իր կարողություններով զորավիգ լինել հայոց պետությանը բոլոր բարի իրագործումներում․ Ամենայն Հայոց Կաթողիկոսն ընդունեց ԱԺ պատգամավորներին",
          "link": "https://www.aravot.am/2026/08/02/1572316/",
          "date": "Sun, 02 Aug 2026 17:51:33 +0000",
          "source_country": "Armenia",
          "category": "border_security",
          "weight": 5.0,
          "confidence": 0.35,
          "ai_model": "deterministic-fallback",
          "ai_category": false,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Եկեղեցին պիտի շարունակի իր կարողություններով զորավիգ լինել հայոց պետությանը բոլոր բարի իրագործումներում․ Ամենայն Հայոց Կաթողիկոսն ընդունեց ԱԺ պատգամավորներին",
          "llm_country_audit_corrected": false,
          "fallback_reason": "llm_attribution_failed",
          "ai_confidence_score": "35.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "«Նույն հրավերն այսօր էլ ուղղված է մեզանից յուրաքանչյուրին՝ բացելու մեր սրտերը այն սիրո առաջ, որը մեզանից առաջ է եկել»",
          "translated_title": "«Նույն հրավերն այսօր էլ ուղղված է մեզանից յուրաքանչյուրին՝ բացելու մեր սրտերը այն սիրո առաջ, որը մեզանից առաջ է եկել»",
          "link": "https://www.aravot.am/2026/08/02/1572314/",
          "date": "Sun, 02 Aug 2026 17:31:40 +0000",
          "source_country": "Armenia",
          "category": "border_security",
          "weight": 5.0,
          "confidence": 0.35,
          "ai_model": "deterministic-fallback",
          "ai_category": false,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "«Նույն հրավերն այսօր էլ ուղղված է մեզանից յուրաքանչյուրին՝ բացելու մեր սրտերը այն սիրո առաջ, որը մեզանից առաջ է եկել»",
          "llm_country_audit_corrected": false,
          "fallback_reason": "llm_attribution_failed",
          "ai_confidence_score": "35.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Ընդդիմադիր պատգամավորները ստացան Վեհափառի օրհնությունը",
          "translated_title": "Ընդդիմադիր պատգամավորները ստացան Վեհափառի օրհնությունը",
          "link": "https://www.aravot.am/2026/08/02/1572313/",
          "date": "Sun, 02 Aug 2026 16:44:50 +0000",
          "source_country": "Armenia",
          "category": "border_security",
          "weight": 5.0,
          "confidence": 0.35,
          "ai_model": "deterministic-fallback",
          "ai_category": false,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Ընդդիմադիր պատգամավորները ստացան Վեհափառի օրհնությունը",
          "llm_country_audit_corrected": false,
          "fallback_reason": "llm_attribution_failed",
          "ai_confidence_score": "35.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Առանձնահատուկ ուշադրություն պետք է դարձնել այն ուտեստներին, որոնք պարունակում են մայոնեզ, թթվասեր, սերուցք կամ այլ արագ փչացող բաղադրիչներ",
          "translated_title": "Առանձնահատուկ ուշադրություն պետք է դարձնել այն ուտեստներին, որոնք պարունակում են մայոնեզ, թթվասեր, սերուցք կամ այլ արագ փչացող բաղադրիչներ",
          "link": "https://www.aravot.am/2026/08/02/1572311/",
          "date": "Sun, 02 Aug 2026 16:19:38 +0000",
          "source_country": "Armenia",
          "category": "border_security",
          "weight": 5.0,
          "confidence": 0.35,
          "ai_model": "deterministic-fallback",
          "ai_category": false,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Առանձնահատուկ ուշադրություն պետք է դարձնել այն ուտեստներին, որոնք պարունակում են մայոնեզ, թթվասեր, սերուցք կամ այլ արագ փչացող բաղադրիչներ",
          "llm_country_audit_corrected": false,
          "fallback_reason": "llm_attribution_failed",
          "ai_confidence_score": "35.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "«Ասում եք՝ տղաներն ընկել են, որ նիստ անենք, չէ, պարոն Ռուբինյան, տղաներն ընկել են, որ մենք չամաչենք Արարատին նայել, Արցախը հայկական համարենք»․ Աննա Գրիգորյան",
          "translated_title": null,
          "link": "https://www.aravot.am/2026/08/02/1572305/",
          "date": "Sun, 02 Aug 2026 14:33:34 +0000",
          "source_country": "Armenia",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Armenian political rhetoric over Artsakh and national identity",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Մանիպուլյատիվ ու անտեղի շահարկում է Դավթյանը համարում ադրբեջանցիների հետ իր շփումների մասին հայտարարությունը",
          "translated_title": null,
          "link": "https://www.aravot.am/2026/08/02/1572307/",
          "date": "Sun, 02 Aug 2026 14:55:54 +0000",
          "source_country": "Armenia",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Armenian official criticizes Azerbaijan interactions",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Armenia begins fish exports to Georgia as Russian restrictions hit industry - Latest news from Azerbaijan",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMinAFBVV95cUxOd1hGZjZRTVNFa3dtYnoyYkY2X2thOHIxN1djUE8tMEFjeVhjQmJPT1pMZTduam1yNzI2clZFSGwwbmNCcWFvWER2VWdyNEhaU0tXZFBSLUdaeU5tcFNoQWFRSWQ2TzdSZGhZWVNfUUF1X3JiWFF0NTZaY01aQmFldk1kekxZOG9Lc3VEQ1BEQXFXM0otMjV4cnRJSUQ?oc=5",
          "date": "Sat, 01 Aug 2026 07:25:25 GMT",
          "source_country": "Georgia",
          "category": "trade_agreement",
          "weight": -2.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Armenia starts fish exports to Georgia amid Russian industry restrictions",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        }
      ]
    },
    "Georgia": {
      "index": 3.72,
      "raw_score": 1.5,
      "events": [
        {
          "title": "Georgian police officer charged with stalking, illegally obtaining nudes",
          "translated_title": null,
          "link": "https://oc-media.org/georgian-police-officer-charged-with-stalking-illegally-obtaining-intimate-photos/",
          "date": "Fri, 31 Jul 2026 12:35:17 +0000",
          "source_country": "Georgia",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "Georgian police officer charged with stalking and illegal image acquisition",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Kobakhidze reiterates that \"foreign agents\" are undermining Georgia's national identity - sovanews.tv",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiuwFBVV95cUxOel9TVlZRNmJxVmJPNUdiNUJ1UF9Wa0p5SjdSTzJOd204azlaQXFWYWtadTJpVjAyd1lpZWVleFN0OFo4VmplZHEzWDlUck5JMW1DbmpldlA0Xy1sZWU2bE5ieXJZZzdlMmxsTTZacEgyX2taNnhCVzdybUJTVHdYTzh3elYwOGxYdkJkS0RwVTJGRS1zalI4ZjQ0N0RLS0RMNzBqdWw1S01JX2VyNWh3ZTVuSFgtM0hIb1930gHAAUFVX3lxTE1fWlZPdHBsWm03YTk0bGZ1WFdTY1ZRR1kyUGdjOFlOU3RRNjdQM3M5N0xINlA1NzBrYk90emhYQWlONkpRLVNjeUxfSWJzVFhxWXdya3E2SUtTM0lqVGlrd3JidEJ2SERabzlkb0dObjdxRjF4MjRYOUZQQlJWaWFEbmhURlBWYXYwZUtMcVZQdEVoSFgwSHJ1aXZ4ZGprRmNBb0FXbTBmM2hlS0RBQjVmUXp4amNDTm9WYjBjeGpmVg?oc=5",
          "date": "Sun, 02 Aug 2026 13:35:35 GMT",
          "source_country": "Georgia",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "Georgian official claims foreign agents threaten national identity",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Georgia welcomes Nauru's decision to revoke recognition of breakaway regions - Latest news from Azerbaijan",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMingFBVV95cUxQNXpBcjZ6V1d1LW1RMDh0TVN6THFvUjlxVlFxajdnUzc4blZ6bi16QU1UWmUzZGh5SGpHVFpLdlM2SGZiMThGeTZVMGF1V0dnU1ZiR0JQaGtPaktoQUVvRjVvczI4eW1hVU9ydWlRMW5mUEM1QW1RVGk1cEVJd19Vd2FQU3p3ZVpfc1VsYVd1bHozaUdHWFlvSnIxdFh2dw?oc=5",
          "date": "Sat, 01 Aug 2026 07:45:29 GMT",
          "source_country": "Georgia",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "Georgia welcomes Nauru's withdrawal of recognition for breakaway regions",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Country music star, 23, arrested in Georgia. Here’s what we know - Cleveland.com",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiswFBVV95cUxPb3ZHTnpydVU4NkdKbTRmUnRqYVJ0TllFblUyRFdoTVViamV6V0RhUFNGcVFscXo0X0pUc2JNVDVHTGIyZG1MLXZMTGtDb1l2b3RGTkw1NnczNllFemxlTDBWSmdzWW9vbjdsWTFxcTdibGFnMmZWZ01IN1BFLW9rb3l1SVdxaHJmWnhTR0s0YXB6Zkl4RExYNmZiY3BJRUdsdmZLSXVQYmtjSVdCakJTVlFYTdIBxwFBVV95cUxNb2VVMEQzNFlMM3BrNENxaWJEOVN5aUg4Sl9SVlNPQXh6TldxaUVnNTZKa0dxSjljc2RrLV82UU5QWkJQekhhbnN4RVljNHBkb3lYT01PWm85VGxWUWtfX01kajdGaDlWdWdGTDBqYndaRkwyNjcwSEkyTE5pdmFseWlUQnZvRGE1SS05YkhWSmxtXzNXam5heWRibTR1ZHEya3AzVWJDbE5BTzhXdWVnUE91T0ZXZFJTSHE4bndpUm5zN2dxWXcw?oc=5",
          "date": "Sun, 02 Aug 2026 11:00:00 GMT",
          "source_country": "Georgia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "Country music star arrested in Georgia",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "შსს-მ გამოძიება დაიწყო არასრულწლოვნების მიმართ შეურაცხმყოფელი მასალის  გავრცელების გამო",
          "translated_title": null,
          "link": "https://netgazeti.ge/news/813170/",
          "date": "Sun, 02 Aug 2026 14:47:47 +0000",
          "source_country": "Georgia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "Georgian-language report on distribution of inappropriate material to minors",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "პლაკატის დაჭერის გამო თორნიკე თოშხუას 5-დღიანი პატიმრობა შეეფარდა",
          "translated_title": null,
          "link": "https://netgazeti.ge/news/813167/",
          "date": "Sun, 02 Aug 2026 12:52:09 +0000",
          "source_country": "Georgia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "Georgian individual's detention extended due to poster-related offense",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "BMG: ვანო ზარდიაშვილი ელექტროსისტემის დირექტორობიდან მოხსნეს",
          "translated_title": null,
          "link": "https://netgazeti.ge/news/813164/",
          "date": "Sun, 02 Aug 2026 12:16:48 +0000",
          "source_country": "Georgia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "Georgian energy official removed from power system directorate",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        }
      ]
    },
    "Greece": {
      "index": 8.68,
      "raw_score": 8.0,
      "events": [
        {
          "title": "Два противопожарни хеликоптера се сблъскаха в Гърция, единият екипаж е загинал",
          "translated_title": "Два противопожарни хеликоптера се сблъскаха в Гърция, единият екипаж е загинал",
          "link": "https://www.dnevnik.bg/burzi-novini/2026/08/02/4941866_dva_protivopojarni_helikoptera_v_gurciia_se_sbluskaha/?ref=rss",
          "date": "Sun, 02 Aug 2026 19:05:00 +0300",
          "source_country": "Bulgaria",
          "category": "military_conflict",
          "weight": 8.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Greece",
          "llm_final_country": "Greece",
          "llm_subject": "Greek helicopter crash during firefighting operation",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        }
      ]
    },
    "Iran": {
      "index": 6.11,
      "raw_score": 3.5,
      "events": [
        {
          "title": "Why did Trump cancel his attack on Iran?",
          "translated_title": "Why did Trump cancel his attack on Iran?",
          "link": "https://www.newarab.com/news/why-did-trump-cancel-his-attack-iran",
          "date": "Sun, 02 Aug 2026 12:44:57 +0100",
          "source_country": "Iraq",
          "category": "military_conflict",
          "weight": 8.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "US military planning against Iran",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Թրամփի հայտարարությունը «պարզապես նոր սուտ» է․ Իրանի ռազմական աղբյուրները հերքում են",
          "translated_title": "Թրամփի հայտարարությունը «պարզապես նոր սուտ» է․ Իրանի ռազմական աղբյուրները հերքում են",
          "link": "https://www.aravot.am/2026/08/02/1572321/",
          "date": "Sun, 02 Aug 2026 19:20:55 +0000",
          "source_country": "Armenia",
          "category": "border_security",
          "weight": 5.0,
          "confidence": 0.35,
          "ai_model": "deterministic-fallback",
          "ai_category": false,
          "ai_reattributed": true,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Iran",
          "llm_subject": "Թրամփի հայտարարությունը «պարզապես նոր սուտ» է․ Իրանի ռազմական աղբյուրները հերքում են",
          "llm_country_audit_corrected": true,
          "fallback_reason": "llm_attribution_failed",
          "ai_confidence_score": "35.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Ιράν: Στο τελικό στάδιο οι συνομιλίες με Ομάν για το Ορμούζ",
          "translated_title": null,
          "link": "https://www.naftemporiki.gr/kosmos/2145950/iran-sto-teliko-stadio-oi-synomilies-me-oman-gia-to-ormoyz/?utm_source=rss&utm_medium=rss&utm_campaign=iran-sto-teliko-stadio-oi-synomilies-me-oman-gia-to-ormoyz",
          "date": "Sun, 02 Aug 2026 17:50:21 +0000",
          "source_country": "Greece",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "Iran-Oman negotiations over Hormuz",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Iran war live: Trump says talks to resume; Tehran urges US to honour MoU",
          "translated_title": null,
          "link": "https://www.aljazeera.com/news/liveblog/2026/8/3/iran-war-live-trump-says-talks-set-to-begin-tehran-urges-us-to-honour-mou?traffic_source=rss",
          "date": "Mon, 03 Aug 2026 00:00:15 +0000",
          "source_country": "Iran",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "US-Iran talks resumption and MoU compliance",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Trump says new round of Iran talks will begin Monday",
          "translated_title": null,
          "link": "https://www.aljazeera.com/news/2026/8/2/trump-says-new-round-of-iran-talks-will-begin-monday?traffic_source=rss",
          "date": "Sun, 02 Aug 2026 23:48:08 +0000",
          "source_country": "Iran",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "New round of US-Iran talks",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Trump says Iran talks set for Monday, no deadline for deal",
          "translated_title": null,
          "link": "https://www.newarab.com/news/trump-says-iran-talks-set-monday-no-deadline-deal",
          "date": "Mon, 03 Aug 2026 00:39:30 +0100",
          "source_country": "Iraq",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "US-Iran nuclear talks scheduled",
          "llm_country_audit_corrected": false,
          "fallback_reason": "country_audit_failed",
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Trump says new talks with Iran to begin Monday",
          "translated_title": null,
          "link": "https://www.newarab.com/news/trump-says-new-talks-iran-begin-monday",
          "date": "Sun, 02 Aug 2026 18:50:17 +0100",
          "source_country": "Iraq",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "New US-Iran talks announced",
          "llm_country_audit_corrected": false,
          "fallback_reason": "country_audit_failed",
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Republicans rate Trump higher on immigration than on Iran",
          "translated_title": null,
          "link": "https://www.newarab.com/news/republicans-rate-trump-higher-immigration-iran",
          "date": "Sun, 02 Aug 2026 16:47:03 +0100",
          "source_country": "Iraq",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "US political rhetoric on Iran policy",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        }
      ]
    },
    "Iraq": {
      "index": 1.0,
      "raw_score": 0.0,
      "events": [
        {
          "title": "Heat triggers fire at Iraq military base: authorities",
          "translated_title": null,
          "link": "https://www.newarab.com/news/heat-triggers-fire-iraq-military-base-authorities",
          "date": "Sun, 02 Aug 2026 18:00:26 +0100",
          "source_country": "Iraq",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Iraq",
          "llm_final_country": "Iraq",
          "llm_subject": "Fire at Iraqi military base",
          "llm_country_audit_corrected": false,
          "fallback_reason": "country_audit_failed",
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Iraq's invasion of Kuwait haunts the region 36 years on",
          "translated_title": null,
          "link": "https://www.newarab.com/news/iraqs-invasion-kuwait-haunts-region-36-years",
          "date": "Sun, 02 Aug 2026 17:47:15 +0100",
          "source_country": "Iraq",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Iraq",
          "llm_final_country": "Iraq",
          "llm_subject": "Historical reflection on Iraq's invasion of Kuwait",
          "llm_country_audit_corrected": false,
          "fallback_reason": "country_audit_failed",
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        }
      ]
    },
    "Syria": {
      "index": 5.14,
      "raw_score": 2.57,
      "events": [
        {
          "title": "Syria arrests three brothers suspected of killing 15 detainees",
          "translated_title": "Syria arrests three brothers suspected of killing 15 detainees",
          "link": "https://www.newarab.com/news/syria-arrests-three-brothers-suspected-killing-15-detainees",
          "date": "Sun, 02 Aug 2026 13:43:52 +0100",
          "source_country": "Iraq",
          "category": "terrorism",
          "weight": 7.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Arrests for detainee killings in Syria",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Israeli occupation forces carry out new incursion into western Daraa countryside",
          "translated_title": "Israeli occupation forces carry out new incursion into western Daraa countryside",
          "link": "https://sana.sy/en/syria/2332729/",
          "date": "Tue, 28 Jul 2026 14:06:35 +0000",
          "source_country": "Syria",
          "category": "border_security",
          "weight": 5.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Israeli forces enter Daraa region",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syria Interior Ministry Moves to Release Ain Mneen Detainees Amid Protests, Shop Closures and Municipal Resignations",
          "translated_title": null,
          "link": "https://syrianobserver.com/syrian-actors/syria-interior-ministry-moves-to-release-ain-mneen-detainees-amid-protests-shop-closures-and-municipal-resignations.html",
          "date": "Sun, 02 Aug 2026 21:03:44 +0000",
          "source_country": "Syria",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Detainee releases amid protests in Syria",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "What the Arrest of Pastor Nihad Hassan Reveals About the “New Syria”",
          "translated_title": null,
          "link": "https://syrianobserver.com/syrian-actors/what-the-arrest-of-pastor-nihad-hassan-reveals-about-the-new-syria.html",
          "date": "Sun, 02 Aug 2026 21:00:17 +0000",
          "source_country": "Syria",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Arrest of pastor reveals religious freedom issues in Syria",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syrian president says ousting former regime was necessary for entire region - Türkiye Today",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiuwFBVV95cUxPcHZ1aEd6em9sSXhKZi13MVl0ZDFKRVQyVkJON3BJeF9mWENnMGZjN3E2T1E3dHo1N0RZSkF0RTJheDl4NFZXVVByZXFGcW0xZEpnM0F4YzBTSDFMMWZkY0UyUG5KT0pkeFlqVi10VF9QaERFakhVeGhTN1NiQW5YcHNGNzJQWkFkdTB4VmVoSlZEbVA0THlZM0FKdVRsTjYyVU1aRl9QX3d6TFBhYzV0TVEtZ29HRTAxR1Rv?oc=5",
          "date": "Sun, 02 Aug 2026 21:21:23 GMT",
          "source_country": "Syria",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Syrian president justifies regime change",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syria: Serving God and people among war and hardship - Herald Malaysia Online",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMimwFBVV95cUxNZlZ4c2pXaXRlMk5OODJfVHJuOHhBbXc4SkJKVWlZMEl2djZfV1RpYVRWN1c1NTRtUl9GeUlUWkhYazhaaHF0OGZrZlYyY0xyVUZFNjhyRkJFSjE5YkdWdDZDSjZjWE92cXhGYVZVVzF0Zno2NHB3d2k3TkZEXzVlZi1CX3NUbnpJQldTN2hqWG9WcTBCZzdLeXhtTQ?oc=5",
          "date": "Sun, 02 Aug 2026 08:13:35 GMT",
          "source_country": "Syria",
          "category": "humanitarian_crisis",
          "weight": 3.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Humanitarian conditions in wartime Syria",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Official Study Tracks 15 Years of Inflation in Syria - Enab Baladi - english.enabbaladi.net",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiowFBVV95cUxPbkZMSXhqQXlhYXc0R0c5MVRvLUVfSHhHOERQMjQ1RVpudlhIb3lYU1lUaVA5dGVURjhzRzE1V0pHdkc2TXNWX19HSE04Ym9zX2dORVR0djdYQXFUZEZIdlFTYkJNOUw3WV91T3o1b1A5MU1BVFJMLTlpdmI1NVFfMnpZTlV1TkxtZUpXWWJyM0JNSU12S2E1b2Y1TDMwZll5VGpZ0gGoAUFVX3lxTE5MUTFtazEzb2lPYTN1dzVBR21PR05rYVpRR2hBbmUtTjcxak0xNS1zamdocEh5Z05BMHV5Wm1XUHN2eUR2WWRmQ0tQR0wzWmpwZEhieTRXRl8wMWY0c1VQU29kUk41SERYSFlaU3FnM01EXzhvQ1BPSGg3YzNmaVgzNElaNmxZeUhqWWczS0t1X3RhQ204U0lNangtaDluSlVQTUlPSDBlZw?oc=5",
          "date": "Sat, 01 Aug 2026 15:44:57 GMT",
          "source_country": "Syria",
          "category": "humanitarian_crisis",
          "weight": 3.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Syrian inflation study reveals economic hardship",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syrian President Sharaa, Saudi Crown Prince Discuss Bilateral Ties and Regional Escalation",
          "translated_title": null,
          "link": "https://syrianobserver.com/foreign-actors/syrian-president-sharaa-saudi-crown-prince-discuss-bilateral-ties-and-regional-escalation.html",
          "date": "Sun, 02 Aug 2026 21:00:39 +0000",
          "source_country": "Syria",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Syria-Saudi bilateral and regional talks",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Based on al-Sharaa’s Remarks, What Are Syria and Israel Negotiating? - Enab Baladi - english.enabbaladi.net",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMitAFBVV95cUxPamFwbDVUOGNiaEhJV3JNNndlVlZsOXk5cjhuWV9ITGE5WXh3RVhMcENna1dvc0plUENwbFQ5Wk41MVlKV0xYNUc4ZjFwZU1tR2haa1hMd1pPN2NUREhVUEhXcFF4ZHdYWENfYWFzVWo0MGVVTmp2U0pXQnp4Uld4dWV3RUVoSnkzclJ6cXRrejB5M2xvSFp4Y08wX2J1eW9hTnZxdmNkbnNFbDhDZUFPUXNDTEnSAboBQVVfeXFMTTVxZkRZQmhYdklSa1p3TjcwUjRSc0t3a0JMckw2NC14RUowSGdZQ0R5eGFoTTAwbjFwV196czdzZVRJUGhhcUJ0QkZPZ3hNcXFfcDdLUjE4Q25FdjNUVjMxTndmYlN6T1pnT2VCSE5EMUpCREd5eXowU0o2TS1ETXgyNDVuNnpOOXc4amtEdnFtc0Q3ckxuUnlGekhscElPM2ZGZWptU2xZdDF4WjNJRHIzT2NpVzE3VC1B?oc=5",
          "date": "Sun, 02 Aug 2026 10:25:55 GMT",
          "source_country": "Syria",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Syria-Israel negotiations",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "President Barzani heads to Damascus for bilateral talks - Shafaq News | Latest breaking news in Iraq and the world - شفق نيوز",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMikAFBVV95cUxQZEwzNTRZdFVBUW1EZnM4SHlzTC03U1U1RkRySEU1OXdNWnAwczdCSUdacjF6aHNmS0oxVmtnRURrcVBJQ3ViYWlKZWtwZ0JGWWg4dHA0aXBITjlvQVdpcDY5U1hfSklUcnEyb1Vjby10amdQQnVfcDQxdDVXNmlXUjdEcW01UzI2R2NMYUJ3b0s?oc=5",
          "date": "Sun, 02 Aug 2026 19:13:11 GMT",
          "source_country": "Syria",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Iraqi Kurdish leader visits Damascus for talks",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syrian Foreign Minister receives outgoing Omani ambassador",
          "translated_title": null,
          "link": "https://sana.sy/en/syria/2332727/",
          "date": "Tue, 28 Jul 2026 14:07:05 +0000",
          "source_country": "Syria",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Syrian FM receives outgoing Omani ambassador",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "As Bank Financing Knocks on Syria’s Door, Who Guarantees the Funds—and Who Ultimately Pays the Debt?",
          "translated_title": null,
          "link": "https://syrianobserver.com/society/as-bank-financing-knocks-on-syrias-door-who-guarantees-the-funds-and-who-ultimately-pays-the-debt.html",
          "date": "Sun, 02 Aug 2026 21:02:10 +0000",
          "source_country": "Syria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Bank financing and debt guarantees for Syria",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syria, South Korea sign education grant, media cooperation agreements",
          "translated_title": null,
          "link": "https://sana.sy/en/politics/2332722/",
          "date": "Tue, 28 Jul 2026 13:47:16 +0000",
          "source_country": "Syria",
          "category": "trade_agreement",
          "weight": -2.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Syria-South Korea education and media agreements",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syria, Egypt discuss expanding economic ties, reviving joint business council",
          "translated_title": null,
          "link": "https://sana.sy/en/economic/2332713/",
          "date": "Tue, 28 Jul 2026 12:40:19 +0000",
          "source_country": "Syria",
          "category": "trade_agreement",
          "weight": -2.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Syria-Egypt economic cooperation expansion",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        }
      ]
    },
    "Bulgaria": {
      "index": 4.04,
      "raw_score": 1.72,
      "events": [
        {
          "title": "Bulgaria: additional truck ban today on the A1, A3 and the road to Kulata - trafficban.com",
          "translated_title": "Bulgaria: additional truck ban today on the A1, A3 and the road to Kulata - trafficban.com",
          "link": "https://news.google.com/rss/articles/CBMiUkFVX3lxTFB2M0dzYmt3S3FqcEtfd2M0TnlDVWxidHMycjI1VHlvZWREaDl0TjRFY0hJR2VrbWhIdE1EakdESENzc3dRdThOMGpyc1d6U0VzR2c?oc=5",
          "date": "Sun, 02 Aug 2026 11:14:11 GMT",
          "source_country": "Bulgaria",
          "category": "border_security",
          "weight": 5.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "Bulgaria bans trucks on A1, A3 and road to Kulata",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Учредено е Независимо сдружение на българските прокурори",
          "translated_title": null,
          "link": "https://www.dnevnik.bg/burzi-novini/2026/08/02/4941904_uchredeno_e_nezavisimo_sdrujenie_na_bulgarskite/?ref=rss",
          "date": "Sun, 02 Aug 2026 21:54:00 +0300",
          "source_country": "Bulgaria",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "Bulgarian prosecutors form independent association",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Адвокати заведоха колективен иск срещу регионалното министерство и пътната агенция",
          "translated_title": null,
          "link": "https://www.dnevnik.bg/burzi-novini/2026/08/02/4941893_advokati_zavedoha_kolektiven_isk_sreshtu_regionalnoto/?ref=rss",
          "date": "Sun, 02 Aug 2026 21:15:00 +0300",
          "source_country": "Bulgaria",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "Bulgarian lawyers file collective claim against regional ministry and road agency",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Moscow’s Embassy in Bulgaria Launches Fundraiser for Russian Troops",
          "translated_title": null,
          "link": "https://balkaninsight.com/techresponses/moscows-embassy-in-bulgaria-launches-fundraiser-for-russian-troops/",
          "date": "Mon, 27 Jun 2022 16:19:43 +0000",
          "source_country": "Bulgaria",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "Russian embassy in Bulgaria fundraises for Russian troops",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "From Today: Bulgaria Introduces Higher Cigarette Prices, Vignettes and Insurance Thresholds - Novinite.com",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMi0gFBVV95cUxPLXNVVDB2QVJVVXFMbDIyZFVMRE1kUFIzRlVBU1RscDFjampVVUhrdE5QYzJ1VmlXRl9YcGh5d3FWbG5lbDZQaHFNOFVyc1RuaTBFVmtSSWdCbHVQZVdtWTBGd0JyX1dUZjRVc19tSXBocjVyTG0xMHdSMC0zdDN4ZUJkMlMzN0ZHeEYxRVBEVmNUajF2ZEI3Vk1CazFsRDc3QVFQSHliN1dIemh0TVpXeUZOSFZHeEkzWWd4ckZUeWw2SGZXYzk4U3NzRTh5TDJZbkE?oc=5",
          "date": "Sat, 01 Aug 2026 07:18:32 GMT",
          "source_country": "Bulgaria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "Bulgaria raises cigarette prices, vignettes and insurance thresholds",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Weather today, forecast for Sunday, August 2: Sunny and hot up to 37° ᐉ News from Fakti.bg - Bulgaria - fakti.bg",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMipAFBVV95cUxPRGNMVWFBT1haN3lVWmZ4cy1QSXc3Zm9rdmF4WElqd1ZNbXhJS2JZa2RITlpCMzFPOXRwTTZIRENSMXdFSjV6MC1ldFNobmtjSXFvLWV6dEx3SGhKMU5jVHMzUmlmaUc3dmppMXRBWG5wMmxULTB0cXlTMVlmOFBRRkE5SFZpM2ZHbkYzMjh3OVQ5NU1vRWgyV01EeF85S01tOGpVUQ?oc=5",
          "date": "Sat, 01 Aug 2026 10:21:00 GMT",
          "source_country": "Bulgaria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "Bulgaria weather forecast: sunny and hot up to 37°C",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Facebook Page Uploaded Misleading Picture of Bulgarian Battalion Fighting In Ukraine",
          "translated_title": null,
          "link": "https://balkaninsight.com/techresponses/facebook-page-uploaded-misleading-picture-of-bulgarian-battalion-fighting-in-ukraine/",
          "date": "Thu, 24 Mar 2022 09:39:36 +0000",
          "source_country": "Bulgaria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "Facebook page posts misleading image of Bulgarian battalion in Ukraine",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Миряни прекъснаха литургия на патриарха заради присъствието на Митрофанова",
          "translated_title": null,
          "link": "https://www.dnevnik.bg/burzi-novini/2026/08/02/4941905_miriani_prekusnaha_liturgiia_na_patriarha_zaradi/?ref=rss",
          "date": "Sun, 02 Aug 2026 22:11:00 +0300",
          "source_country": "Bulgaria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "Bulgarians interrupt patriarch's liturgy over Mitrofanova's presence",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Юли 2026 г. е бил един от най-хладните през последните две десетилетия",
          "translated_title": null,
          "link": "https://www.dnevnik.bg/burzi-novini/2026/08/02/4941892_juli_2026_g_e_bil_edin_ot_nai-hladnite_meseci_juli/?ref=rss",
          "date": "Sun, 02 Aug 2026 20:56:00 +0300",
          "source_country": "Bulgaria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "July 2026 among coldest in last two decades in Bulgaria",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        }
      ]
    }
  },
  "history": [
    {
      "timestamp": "2026-08-01T02:15:53.678176",
      "main_index": 5.77,
      "index": 5.77,
      "type": "historical"
    },
    {
      "timestamp": "2026-08-01T06:26:52.369319",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-08-01T09:55:48.468841",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-08-01T11:16:18.244830",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-08-01T13:08:02.235407",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-08-01T14:58:27.566852",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-08-01T16:57:54.803892",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-08-01T19:03:02.753374",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-08-01T20:46:31.646746",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-08-01T22:51:28.975677",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-08-02T06:31:58.858415",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-08-02T09:54:05.135458",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-08-02T11:16:53.684626",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-08-02T13:09:31.119581",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-08-02T15:00:11.245903",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-08-02T16:56:36.957435",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-08-02T19:03:55.917409",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-08-02T20:49:18.075206",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-08-02T22:52:53.975914",
      "main_index": 7.29,
      "index": 7.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-08-03T02:15:42.285276",
      "main_index": 4.69,
      "index": 4.69,
      "type": "historical"
    }
  ],
  "forecast": [
    {
      "timestamp": "2026-08-03T03:15:42.285276",
      "index": 6.92,
      "main_index": 6.92,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-08-03T04:15:42.285276",
      "index": 6.91,
      "main_index": 6.91,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-08-03T05:15:42.285276",
      "index": 6.89,
      "main_index": 6.89,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-08-03T06:15:42.285276",
      "index": 6.88,
      "main_index": 6.88,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-08-03T07:15:42.285276",
      "index": 6.86,
      "main_index": 6.86,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-08-03T08:15:42.285276",
      "index": 6.84,
      "main_index": 6.84,
      "confidence": 0.3,
      "type": "forecast"
    }
  ],
  "methodology": {
    "name": "LLM Border Threat Taxonomy",
    "description": "OpenRouter free routing chooses the final country attribution and canonical threat category for each headline.",
    "weights": {
      "military_conflict": 8.0,
      "terrorism": 7.0,
      "border_security": 5.0,
      "political_instability": 4.0,
      "humanitarian_crisis": 3.0,
      "diplomatic_tensions": 2.5,
      "trade_agreement": -2.0,
      "neutral": 0.0
    },
    "formula": "PerCountry = 1 + 9*(1 - exp(-avg(weight)/5 * 1.2)); Composite = weighted_avg(PerCountry)",
    "scale": {
      "min": 1.0,
      "max": 10.0,
      "thresholds": {
        "STABLE": [
          1.0,
          4.0
        ],
        "ELEVATED": [
          4.0,
          7.0
        ],
        "CRITICAL": [
          7.0,
          10.0
        ]
      }
    }
  },
  "briefing": {
    "regional_summary_6h": {
      "slot_start": "2026-08-02T18:00:00Z",
      "slot_end": "2026-08-03T00:00:00Z",
      "generated_at": "2026-08-03T02:15:41Z",
      "next_refresh_at": "2026-08-03T06:00:00Z",
      "window_hours": 6,
      "source_event_count": 12,
      "source_countries": [
        "Armenia",
        "Bulgaria",
        "Greece",
        "Iran",
        "Syria"
      ],
      "headline": "Border-country reporting stayed active across 5 neighbors.",
      "bullets": [
        "12 scored signals passed the feed and coverage gates for the completed window.",
        "Country placement uses source-country attribution while automated re-attribution is unavailable.",
        "Review high-weight events directly before treating the regional picture as settled."
      ],
      "watch": null
    }
  }
};